import {Color} from 'excalibur';

import {LevelDefinition} from "./type.ts";
import {TILE_SIZE} from "../constants";

export const level: LevelDefinition = {
    objects: [
        [   'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    ],
        [   'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    ],
        [   'G',    'G',    'WTL',  'WT',   'WT',   'WT',   'WT',   'WTR',  'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    ],
        [   'G',    'G',    'WL',   'W',    'W',    'W',    'W',    'WR',   'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    ],
        [   'G',    'G',    'WBL',  'WB',   'WB',   'WB',   'WB',   'WBR',  'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    ],
        [   'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    ],
        [   'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    ],
        [   'G',    'G',    'WTL',  'WT',   'WT',   'WT',   'WT',   'WT',   'WT',   'WTR',  'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    ],
        [   'G',    'G',    'WL',   'W',    'W',    'W',    'W',    'W',    'W',    'WR',   'G',    'G',    'WTL',  'WT',   'WT',   'WT',   'WT',   'WT',   'WT',   'WT',   'WT',   'WT'    ],
        [   'G',    'G',    'WBL',  'WB',   'WB',   'WB',   'WB',   'WB',   'WB',   'WBR',  'G',    'G',    'WL',   'W',    'W',    'W',    'W',    'W',    'W',    'W',    'W',    'W',    ],
        [   'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'WL',   'W',    'W',    'W',    'W',    'W',    'W',    'W',    'W',    'W',    ],
        [   'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'WBL',  'WB',   'WB',   'WB',   'WB',   'WB',   'WB',   'WB',   'WB',   'WB',   ],
        [   'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    'G',    ],
    ],
    rocks: [
        {x: TILE_SIZE*3, y: 0},
        {x: TILE_SIZE*3, y: TILE_SIZE},
        {x: TILE_SIZE*0.5, y: TILE_SIZE*6},
        {x: TILE_SIZE, y: TILE_SIZE*7},
        {x: 12*TILE_SIZE, y: TILE_SIZE*2},
        {x: 11.5*TILE_SIZE, y: TILE_SIZE*1.6},
        {x: 11*TILE_SIZE, y: TILE_SIZE},
        {x: 12*TILE_SIZE, y: TILE_SIZE*0.5},
        {x: 13*TILE_SIZE, y: TILE_SIZE*3},
        {x: 13*TILE_SIZE, y: TILE_SIZE*4},
        {x: 13.5*TILE_SIZE, y: TILE_SIZE*3.5},
        {x: 0.3*TILE_SIZE, y: TILE_SIZE*11.5},
        {x: TILE_SIZE, y: TILE_SIZE*12},
        {x: 17.2*TILE_SIZE, y: TILE_SIZE*6.4},
        {x: 17.2*TILE_SIZE, y: TILE_SIZE*5},
    ],
    smallRocks: [
        {x: 0, y: TILE_SIZE*7},
        {x: TILE_SIZE*0.2, y: TILE_SIZE*6.5},
        {x: TILE_SIZE*1.6, y: TILE_SIZE*6.3},
        {x: TILE_SIZE*7.7, y: TILE_SIZE*3.5},
        {x: TILE_SIZE*8.3, y: TILE_SIZE*3.8},
        {x: TILE_SIZE*5.6, y: TILE_SIZE*9.8},
        {x: TILE_SIZE*2.5, y: TILE_SIZE*1.6},
        {x: TILE_SIZE*11.5, y: -TILE_SIZE*0.2},
        {x: TILE_SIZE*12.5, y: TILE_SIZE*2.6},
        {x: 14.5*TILE_SIZE, y: TILE_SIZE*7.3},
        {x: 19*TILE_SIZE, y: TILE_SIZE},
        {x: 20.7*TILE_SIZE, y: TILE_SIZE*2.5},
    ],
    bushBlockers: [
        {x: TILE_SIZE*0.5,y: TILE_SIZE*8},
        {x: TILE_SIZE*6,y: TILE_SIZE*0.5},
        {x: TILE_SIZE*8.2,y: TILE_SIZE*3},
        {x: 13*TILE_SIZE, y: TILE_SIZE*4.5},
        {x: 15.2*TILE_SIZE, y: TILE_SIZE*6.8},
        {x: 16*TILE_SIZE, y: TILE_SIZE*6.2},
        {x: 16.8*TILE_SIZE, y: TILE_SIZE*5.6},
        {x: 16.8*TILE_SIZE, y: TILE_SIZE*5.6},
    ],
    waterProps: [
        {x: TILE_SIZE * 2.5, y: TILE_SIZE*2.5},
        {x: TILE_SIZE * 3, y: TILE_SIZE*3},
        {x: TILE_SIZE * 4, y: TILE_SIZE*3.5},
        {x: TILE_SIZE * 3, y: TILE_SIZE*3.5},
        {x: TILE_SIZE * 5.5, y: TILE_SIZE*8.5},
        {x: TILE_SIZE * 6, y: TILE_SIZE*8},
        {x: TILE_SIZE * 6, y: TILE_SIZE*8.5},
        {x: TILE_SIZE * 3, y: TILE_SIZE*7.5},
        {x: TILE_SIZE * 8, y: TILE_SIZE*8.5},
        {x: TILE_SIZE * 8.5, y: TILE_SIZE*7.5},
        {x: 18.5*TILE_SIZE, y: TILE_SIZE*10},
        {x: 19.5*TILE_SIZE, y: TILE_SIZE*10},
        {x: 20.5*TILE_SIZE, y: TILE_SIZE*10},
        {x: 18*TILE_SIZE, y: TILE_SIZE*9},
        {x: 17*TILE_SIZE, y: TILE_SIZE*9},
        {x: 19*TILE_SIZE, y: TILE_SIZE*9},
        {x: 20.5*TILE_SIZE, y: TILE_SIZE*0.5},
        {x: 18.5*TILE_SIZE, y: TILE_SIZE*1.5},
    ],
    animals: [
        {
            type: 'bear',
            x: TILE_SIZE * 0.5,
            y: TILE_SIZE * 8.5,
        },
        {
            type: 'deer',
            x: TILE_SIZE * 4.5,
            y: TILE_SIZE * 1.1,
        },
        {
            type: 'frog',
            x: TILE_SIZE * 20,
            y: TILE_SIZE * 10.5,
        },
        {
            type: 'condor',
            x: TILE_SIZE * 20,
            y: TILE_SIZE,
        },
    ],
    backgroundColor: new Color(140, 154, 69),
}
